### ISSUE TITLE
It does not seem to work

### ISSUE THREAD

**Issue by Crowley007** [Blackkatt/ToggleThatEpisode#1]
**Hello! I've been trying to get this to work, but "Kodi callbacks" never runs the script, and when I try to run it manually I get these errors in powershell:**

<Invoke-RestMethod : The remote server returned an error: (500) Internal Server Error.
At C:\Onedrive\ToggleThatEpisode-master\ToggleThatEpisode.ps1:94 char:13
- $Episodes = Invoke-RestMethod -Uri $getEpisodes$SerieId -Method Get - ...
-             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
  - FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The remote server returned an error: (500) Internal Server Error.
At C:\Onedrive\ToggleThatEpisode-master\ToggleThatEpisode.ps1:106 char:11
- $Toggle = Invoke-RestMethod -Uri $getEpisodes$EpisodeId -Method Put - ...
-           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
  - FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
    >

**And these in Sonarr logs:**

NzbDroneErrorPipeline
Request Failed: Error reading integer. Unexpected token: StartObject. Path 'SeriesId', line 2, position 19.
21:20

NzbDroneErrorPipeline
Request Failed: Input string was not in a correct format.

**I would really love to get this to work!**

**Comment by W3Warp** [comment]
Hi,

I will try to help you solve this. I will have a quick look now and dig into it tomorrow.

**Comment by Crowley007** [comment]
Thank you very much! This would be a really useful feature for me If I can get it working.

**Comment by W3Warp** [comment]
Okey, so enable debugging in sonarr. I have to see what is sent.

When it works, it looks something like this

```
[Debug] Api: [GET] /api/series: 200.OK (161 ms)
[Debug] Api: [GET] /api/episode?SeriesId=188: 200.OK (15 ms)
[Debug] EpisodeService: Monitored flag for Episode:23765 was set to False
[Debug] Api: [PUT] /api/episode?SeriesId=23765: 202.Accepted (129 ms)
```

Enable debug logging in sonarr, 
http://127.0.0.1:8989/settings/general

then restart sonarr I think (i use the console)

**Comment by Crowley007** [comment]
**When I open the error messages the first one reads:**

Message 
Request Failed: Input string was not in a correct format.

Exception 
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Nancy.DynamicDictionaryValue.op_Implicit(DynamicDictionaryValue dynamicValue)
   at NzbDrone.Api.Episodes.EpisodeModule.GetEpisodes() in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\Episodes\EpisodeModule.cs:line 28
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__32_0(Object options) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\REST\RestModule.cs:line 111
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**And the second:**

Message 
Request Failed: Error reading integer. Unexpected token: StartObject. Path 'SeriesId', line 2, position 19.

Exception 
Newtonsoft.Json.JsonReaderException: Error reading integer. Unexpected token: StartObject. Path 'SeriesId', line 2, position 19.
   at Newtonsoft.Json.JsonReader.ReadAsInt32Internal()
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at NzbDrone.Api.Extensions.ReqResExtensions.FromJson(Stream body, Type type) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\Extensions\ReqResExtensions.cs:line 31
   at NzbDrone.Api.Extensions.ReqResExtensions.FromJson[T](Stream body, Type type) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\Extensions\ReqResExtensions.cs:line 24
   at NzbDrone.Api.Extensions.ReqResExtensions.FromJson[T](Stream body) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\Extensions\ReqResExtensions.cs:line 19
   at NzbDrone.Api.REST.RestModule`1.ReadResourceFromRequest(Boolean skipValidate) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\REST\RestModule.cs:line 188
   at NzbDrone.Api.REST.RestModule`1.<set_UpdateResource>b__44_0(Object options) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\REST\RestModule.cs:line 170
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by Blackkatt** [comment]
Yeah, that tells me nothing. You have to enable debug logging in sonarr, 

http://127.0.0.1:8989/settings/general

then restart sonarr I think (i use the console)

**Comment by Crowley007** [comment]
Ok, I just noticed the debug log goes in to a separate file. It's attached.

**Comment by W3Warp** [comment]
Yeah, the series id is not included that's why sonarr throws and error. Now we have to figure out why. Give me a sec.

**Comment by Blackkatt** [comment]
Hmm, you know this does not work for movies right? I see

16-10-25 21:51:18.2|Debug|Parser|Parsing string 'Batman.Return.of.the.Caped.Crusaders.2016.BluRay.Remux.1080p.AVC.DTS-HD.MA.5.1-ZQ.cp(tt5973626)'
16-10-25 21:51:18.2|Debug|Parser|Episode Parsed. Batman Return of the Caped Crusaders - S20E16 
16-10-25 21:51:18.2|Debug|Parser|Language parsed: English
16-10-25 21:51:18.2|Debug|QualityParser|Trying to parse quality for Batman.Return.of.the.Caped.Crusaders.2016.BluRay.Remux.1080p.AVC.DTS-HD.MA.5.1-ZQ.cp(tt5973626)

why is that even in the sonarr log? =)

**Comment by Crowley007** [comment]
But yeah, I was running the script manually  to test since Kodi never ran it for some reason. Do I need to set event for playback start? I tired this once but it still didn't seem to run..

**Comment by W3Warp** [comment]
Yes, set it to playback start. If you want to try it manually, start playback in kodi, alt+tab, run the script and look in sonarr. Run the sonarr console its easier for you. The "episode" has to be running for it to work. Else we don't know what we're going to toggle or the show itself =)

**Comment by Crowley007** [comment]
Ok, it worked manually, but not when Kodi callback runs it. Strange.

**Comment by W3Warp** [comment]
Then there's a config issue with callbacks. Make sure you've done exactly like I've explained (or tried too) =)
1. in "Kodi Callbacks" settings/tasks/task select script. ? http://kodi.wiki/index.php?title=Add-on:Kodi%20Callbacks
2. click "script executable file -browser" select "ToggleThatEpisodeLNCHR.cmd"

**Comment by Crowley007** [comment]
Yes, when I enable notifications it says it runs the script, but nothing appears in the Sonarr logs so I'm guessing it does not run. Well, at least I know where the problem is.

**Comment by Crowley007** [comment]
Ok, Problem solved! The path to the script was too long for Kodi for some reason and I didn't think to check that. Thank you very much for the support and for the great script, very useful! (Perhaps you could edit out the personal bits about my log, I will do the same. :) )

**Comment by W3Warp** [comment]
Great! and thanks. Will do.

> The path to the script was too long

Good to know. I did not think of that either.
